### ISSUE TITLE
Not working for actions with params

### ISSUE THREAD

**Issue by przyb** [Fuphoenixes/piniaPluginLoading#2]
Hi, first of all, thanks for a neat little plugin. I've just started testing it to check if it fits my requirements.  The problem I've encountered is that the typing for `$loading` that you've declared won't work for actions with params.  A possible solution would be changing the module declaration as follows:

```
declare module 'pinia' {
	// eslint-disable-next-line
	export interface PiniaCustomProperties<Id, S, G, A> {
		$loading: {
			[K in keyof A as A[K] extends (...args: any) => Promise<any> ? K : never]: Ref<boolean>;
		};
	}
}
```

**Comment by Fuphoenixes** [comment]
thanks! fixed in  v2.0.0
